### ISSUE TITLE
PostError: PostError: network-failure

### ISSUE THREAD

**Issue by cproudlock** [IAdventurer01/actual-simplefin-docker#1]
I've been running into the following error when trying to sync my accounts:

```
/opt/actual-simplefin-sync/node_modules/@actual-app/api/dist/app/bundle.api.js:44588
                    throw new _errors__WEBPACK_IMPORTED_MODULE_1__.PostError('network-failure');
                          ^

PostError: PostError: network-failure
    at post (/opt/actual-simplefin-sync/node_modules/@actual-app/api/dist/app/bundle.api.js:44588:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handlers.subscribe-sign-in (/opt/actual-simplefin-sync/node_modules/@actual-app/api/dist/app/bundle.api.js:43425:29) {
  type: 'PostError',
  reason: 'network-failure',
  meta: undefined
}
```

**Comment by cproudlock** [comment]
Resolved, I had specified the wrong port under simplefin.
